const util = require('util');

  let accion = [
      { title: '300', year: 2006, genre: "Accion" },
      { title: 'Apocalypto', year: 2006, genre: "Accion" },
      { title: 'Assault on Precinct 13', year: 2005, genre: "Accion" },
      { title: 'Batman Begins', year: 2005, genre: "Accion" },
      { title: 'Brawl in Cell Block 99', year: 2017, genre: "Accion" },
      { title: 'Casino Royale', year: 2006, genre: "Accion" },
      { title: 'Collateral', year: 2004, genre: "Accion" },
      { title: 'Crawl', year: 2019, genre: "Accion" },
      { title: 'Death Proof', year: 2007, genre: "Accion" },
      { title: 'Die Hard', year: 1988, genre: "Accion" },
      { title: 'Die Hard with a Vengeance', year: 1995, genre: "Accion" },
      { title: 'Enemy Mine', year: 1985, genre: "Accion" },
      { title: 'Enemy of the State', year: 1998, genre: "Accion" },
      { title: 'Face/Off', year: 1997, genre: "Accion" },
      { title: 'Fast & Furious 5', year: 2011, genre: "Accion" },
      { title: 'First Blood', year: 1982, genre: "Accion" },
      { title: 'Gone in 60 Seconds', year: 2000, genre: "Accion" },
      { title: 'Highlander', year: 1986, genre: "Accion" },
      { title: 'I, Robot', year: 2004, genre: "Accion" },
      { title: 'John Wick', year: 2014, genre: "Accion" },
      { title: 'Kill Bill: Vol. 1', year: 2003, genre: "Accion" },
      { title: 'Kill Bill: Vol. 2', year: 2004, genre: "Accion" },
      { title: 'Law Abiding Citizen', year: 2009, genre: "Accion" },
      { title: 'Limitless', year: 2011, genre: "Accion" },
      { title: 'Lock Up', year: 1989, genre: "Accion"},
      { title: 'Mad Max: Fury Road', year: 2015, genre: "Accion" },
      { title: 'Man on Fire', year: 2004, genre: "Accion" },
      { title: 'Mission Impossible', year: 1996, genre: "Accion" },
      { title: 'Mission Impossible III', year: 2006, genre: "Accion" },
      { title: "Ocean's Eleven", year: 2001, genre: "Accion" },
      { title: 'Oldboy', year: 2003, genre: "Accion" },
      { title: 'Olympus Has Fallen', year: 2013, genre: "Accion" },
      { title: 'Patriot Games', year: 1992, genre: "Accion" },
      { title: 'Resident Evil', year: 2002, genre: "Accion" },
      { title: 'Ronin', year: 1998, genre: "Accion" },
      { title: 'Rush', year: 2013, genre: "Accion" },
      { title: 'Shooter', year: 2007, genre: "Accion" },
      { title: 'Sin City', year: 2005, genre: "Accion" },
      { title: 'Southpaw', year: 2015, genre: "Accion" },
      { title: 'Speed', year: 1994, genre: "Accion" },
      { title: 'Taken', year: 2008, genre: "Accion" },
      { title: 'The Boondock Saints', year: 1999, genre: "Accion" },
      { title: 'The Bourne Identity', year: 2002, genre: "Accion" },
      { title: 'The Bourne Supremacy', year: 2004, genre: "Accion" },
      { title: 'The Bourne Ultimatum', year: 2007, genre: "Accion" },
      { title: 'The Dark Knight', year: 2008, genre: "Accion" },
      { title: 'The Dark Knight Rises', year: 2012, genre: "Accion" },
      { title: 'The Equalizer', year: 2014, genre: "Accion" },
      { title: 'The Fast and the Furious', year: 2001, genre: "Accion" },
      { title: 'The Fugitive', year: 1993, genre: "Accion" },
      { title: 'The Hunt for Red October', year: 1990, genre: "Accion" },
      { title: 'The Italian Job', year: 2003, genre: "Accion" },
      { title: 'The Jackal', year: 1997, genre: "Accion" },
      { title: 'The Rock', year: 1996, genre: "Accion" },
      { title: 'The Score', year: 2001, genre: "Accion" },
      { title: 'The Wolverine', year: 2013, genre: "Accion" },
      { title: 'Top Gun', year: 1986, genre: "Accion" },
      { title: 'Top Gun: Maverick', year: 2022, genre: "Accion" },
      { title: 'Transformers', year: 2007, genre: "Accion" },
      { title: 'True Lies', year: 1994, genre: "Accion" },
      { title: 'U-571', year: 2000, genre: "Accion" },
      { title: 'Warrior', year: 2011, genre: "Accion" },
      { title: 'World War Z', year: 2013, genre: "Accion" }
  ]

  let argentinas = [
      { title: '9 Reinas', year: 2000, genre: "Argentina" },
      { title: 'Argentina, 1985', year: 2022, genre: "Argentina" },
      { title: 'Caballos Salvajes', year: 1995, genre: "Argentina" },
      { title: 'Carancho', year: 2010, genre: "Argentina" },
      { title: 'Cenizas del Paraíso', year: 1997, genre: "Argentina" },
      { title: 'El Aura', year: 2005, genre: "Argentina" },
      { title: 'El Clan', year: 2015, genre: "Argentina" },
      { title: 'El Hijo de la Novia', year: 2001, genre: "Argentina" },
      { title: 'El Patrón: Radiografía de un Crimen', year: 2014, genre: "Argentina" },
      { title: 'Elefante Blanco', year: 2012, genre: "Argentina" },
      { title: 'Luna de Avellaneda', year: 2004, genre: "Argentina" },
      { title: 'Séptimo', year: 2013, genre: "Argentina" },
      { title: 'Tiempo de Valientes', year: 2005, genre: "Argentina" },
      { title: 'Un Oso Rojo', year: 2002, genre: "Argentina" },
      { title: 'XXY', year: 2007, genre: "Argentina" }
  ]
  
  let comedias = [
      { title: 'Ace Ventura: Pet Detective', year: 1994, genre: "Comedia" },
      { title: 'Ace Ventura: When Nature Calls', year: 1995, genre: "Comedia" },
      { title: 'Alfie', year: 2004, genre: "Comedia" },
      { title: 'Along Came Polly', year: 2004, genre: "Comedia" },
      { title: 'American Pie', year: 1999, genre: "Comedia" },
      { title: 'American Psycho', year: 2000, genre: "Comedia" },
      { title: 'Anger Management', year: 2003, genre: "Comedia" },
      { title: 'Annie Hall', year: 1977, genre: "Comedia" },
      { title: 'Army of Darkness', year: 1992, genre: "Comedia" },
      { title: 'As Good as It Gets', year: 1997, genre: "Comedia" },
      { title: 'Burn After Reading', year: 2008, genre: "Comedia" },
      { title: 'Dodgeball: A True Underdog Story', year: 2004, genre: "Comedia" },
      { title: 'Dumb and Dumber', year: 1994, genre: "Comedia" },
      { title: 'Happy Death Day', year: 2017, genre: "Comedia" },
      { title: 'Hitch', year: 2005, genre: "Comedia" },
      { title: 'Hot Shots! Part Deux', year: 1993, genre: "Comedia" },
      { title: 'I Care a Lot', year: 2020, genre: "Comedia" },
      { title: 'Liar Liar', year: 1997, genre: "Comedia" },
      { title: 'Love & Other Drugs', year: 2010, genre: "Comedia" },
      { title: 'Manhattan', year: 1979, genre: "Comedia" },
      { title: 'Mars Attacks!', year: 1996, genre: "Comedia" },
      { title: 'Meet the Parents', year: 2000, genre: "Comedia" },
      { title: "My Best Friend's Wedding", year: 1997, genre: "Comedia" },
      { title: 'Old School', year: 2003, genre: "Comedia" },
      { title: 'Palm Springs', year: 2020, genre: "Comedia" },
      { title: 'Patch Adams', year: 1998, genre: "Comedia" },
      { title: 'Poor Things', year: 2023, genre: "Comedia" },
      { title: 'Road Trip', year: 2000, genre: "Comedia" },
      { title: 'School of Rock', year: 2003, genre: "Comedia" },
      { title: 'Shrek', year: 2001, genre: "Comedia" },
      { title: 'Sideways', year: 2004, genre: "Comedia" },
      { title: 'Silver Linings Playbook', year: 2012, genre: "Comedia" },
      { title: 'Snatch', year: 2000, genre: "Comedia" },
      { title: 'Stuck on You', year: 2003, genre: "Comedia" },
      { title: 'Super Troopers', year: 2001, genre: "Comedia" },
      { title: 'Superbad', year: 2007, genre: "Comedia" },
      { title: 'Team America: World Police', year: 2004, genre: "Comedia" },
      { title: 'Ted', year: 2012, genre: "Comedia" },
      { title: 'Thank You for Smoking', year: 2005, genre: "Comedia" },
      { title: 'The 40-Year-Old Virgin', year: 2005, genre: "Comedia" },
      { title: 'The Big Lebowski', year: 1998, genre: "Comedia" },
      { title: 'The Devil Wears Prada', year: 2006, genre: "Comedia"},
      { title: 'The Hangover', year: 2009, genre: "Comedia" },
      { title: 'The Terminal', year: 2004, genre: "Comedia" },
      { title: "There's Something About Mary", year: 1998, genre: "Comedia" },
      { title: 'Three Billboards Outside Ebbing, Missouri', year: 2017, genre: "Comedia" },
      { title: 'Top Secret!', year: 1984, genre: "Comedia" },
      { title: 'Vicky Cristina Barcelona', year: 2008, genre: "Comedia" },
      { title: "Wayne's World", year: 1992, genre: "Comedia" },
      { title: 'Wedding Crashers', year: 2005, genre: "Comedia" },
      { title: 'When Harry Met Sally...', year: 1989, genre: "Comedia" },
      { title: 'Zoolander', year: 2001, genre: "Comedia" }
  ]
  
  let fantastico = [
      { title: "The Lord of the Rings: The Return of the King", year: 2003, genre: "Fantastico"},
      { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, genre: "Fantastico"},
      { title: "The Lord of the Rings: The Two Towers", year: 2002, genre: "Fantastico"},
      { title: 'Avatar', year: 2009, genre: "Fantastico"},
      { title: 'Big Fish', year: 2003, genre: "Fantastico" },
      { title: 'Clash of the Titans', year: 2010, genre: "Fantastico" },
      { title: 'Maleficent', year: 2014, genre: "Fantastico" },
      { title: "Pan's Labyrinth", year: 2006, genre: "Fantastico" },
      {
        title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
        year: 2003,
        genre: "Fantastico"
      },
      { title: 'Sleepy Hollow', year: 1999, genre: "Fantastico" },
      { title: 'Star Wars: Episode I - The Phantom Menace', year: 1999, genre: "Fantastico" },
      { title: 'Star Wars: Episode II - Attack of the Clones', year: 2002, genre: "Fantastico" },
      { title: 'Star Wars: Episode III - Revenge of the Sith', year: 2005, genre: "Fantastico" },
      { title: 'Star Wars: Episode IV - A New Hope', year: 1977, genre: "Fantastico" },
      {
        title: 'Star Wars: Episode V - The Empire Strikes Back',
        year: 1980, 
        genre: "Fantastico"
      },
      { title: 'Star Wars: Episode VI - Return of the Jedi', year: 1983, genre: "Fantastico" },
      { title: 'The Hobbit: An Unexpected Journey', year: 2012, genre: "Fantastico" },
      { title: 'The Hobbit: The Battle of the Five Armies', year: 2014, genre: "Fantastico" },
      { title: 'The Hobbit: The Desolation of Smaug', year: 2013, genre: "Fantastico" },
      {
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        year: 2001,
        genre: "Fantastico"
      },
      {
        title: 'The Lord of the Rings: The Return of the King',
        year: 2003,
        genre: "Fantastico"
      },
      { title: 'The Lord of the Rings: The Two Towers', year: 2002, genre: "Fantastico" },
      { title: 'Underworld', year: 2003, genre: "Fantastico" },
      { title: 'Van Helsing', year: 2004, genre: "Fantastico" },
      { title: 'Warcraft', year: 2016, genre: "Fantastico" }
  ]
  
  let aventura = [
      { title: 'Dawn of the Planet of the Apes', year: 2014, genre: "Aventura" },
      { title: 'Dune', year: 2021, genre: "Aventura" },
      { title: 'Indiana Jones and the Last Crusade', year: 1989, genre: "Aventura" },
      { title: 'Indiana Jones and the Temple of Doom', year: 1984, genre: "Aventura" },
      { title: 'Jurassic Park', year: 1993, genre: "Aventura" },
      { title: 'National Treasure', year: 2004, genre: "Aventura" },
      { title: 'Noah', year: 2014, genre: "Aventura" },
      { title: 'Prince of Persia: The Sands of Time', year: 2010, genre: "Aventura" },
      { title: 'Raiders of the Lost Ark', year: 1981, genre: "Aventura" },
      { title: 'Rise of the Planet of the Apes', year: 2011, genre: "Aventura" },
      { title: 'The Count of Monte Cristo', year: 2002, genre: "Aventura" },
      { title: 'The Hunger Games', year: 2012, genre: "Aventura" },
      { title: 'The Hunger Games: Catching Fire', year: 2013, genre: "Aventura" },
      { title: 'The Hunger Games: Mockingjay - Part 1', year: 2014, genre: "Aventura" },
      { title: 'The Hunger Games: Mockingjay - Part 2', year: 2015, genre: "Aventura" },
      {
        title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
        year: 2023,
        genre: "Aventura"
      },
      { title: 'The Physician', year: 2013, genre: "Aventura" },
      { title: 'Tomb Raider', year: 2018, genre: "Aventura" },
      { title: 'Troy', year: 2004, genre: "Aventura" },
      { title: 'War for the Planet of the Apes', year: 2017, genre: "Aventura" }
  ]
  
  let csFiccion = [
      { title: '12 Monkeys', year: 1995, genre: "Ciencia Ficcion" },
      { title: 'A Quiet Place', year: 2018, genre: "Ciencia Ficcion" },
      { title: 'A Quiet Place II', year: 2020, genre: "Ciencia Ficcion" },
      { title: 'Alien', year: 1979, genre: "Ciencia Ficcion" },
      { title: 'Alien 3', year: 1992, genre: "Ciencia Ficcion" },
      { title: 'Aliens', year: 1986, genre: "Ciencia Ficcion" },
      { title: 'Annihilation', year: 2018, genre: "Ciencia Ficcion" },
      { title: 'Another Earth', year: 2011, genre: "Ciencia Ficcion" },
      { title: 'Back to the Future', year: 1985, genre: "Ciencia Ficcion" },
      { title: 'Blade Runner', year: 1982, genre: "Ciencia Ficcion" },
      { title: 'Blade Runner 2049', year: 2017, genre: "Ciencia Ficcion" },
      { title: 'Coherence', year: 2013, genre: "Ciencia Ficcion" },
      { title: 'Contact', year: 1997, genre: "Ciencia Ficcion" },
      { title: 'Edge of Tomorrow', year: 2014, genre: "Ciencia Ficcion" },
      { title: 'El Hoyo', year: 2019, genre: "Ciencia Ficcion" },
      { title: 'Ex Machina', year: 2014, genre: "Ciencia Ficcion" },
      { title: 'Gattaca', year: 1997, genre: "Ciencia Ficcion" },
      { title: 'Gravity', year: 2013, genre: "Ciencia Ficcion" },
      { title: 'Her', year: 2013, genre: "Ciencia Ficcion" },
      { title: 'I Am Legend', year: 2007, genre: "Ciencia Ficcion" },
      { title: 'I Origins', year: 2014, genre: "Ciencia Ficcion" },
      { title: 'Inception', year: 2010, genre: "Ciencia Ficcion" },
      { title: 'Interstellar', year: 2014, genre: "Ciencia Ficcion" },
      { title: 'Melancholia', year: 2011, genre: "Ciencia Ficcion" },
      { title: 'Minority Report', year: 2002, genre: "Ciencia Ficcion" },
      { title: 'Moon', year: 2009, genre: "Ciencia Ficcion" },
      { title: 'Oxygen', year: 2021, genre: "Ciencia Ficcion" },
      { title: 'Possessor', year: 2020, genre: "Ciencia Ficcion" },
      { title: 'Predator', year: 1987, genre: "Ciencia Ficcion" },
      { title: 'Predestination', year: 2014, genre: "Ciencia Ficcion" },
      { title: 'Prometheus', year: 2012, genre: "Ciencia Ficcion" },
      { title: 'Signs', year: 2002, genre: "Ciencia Ficcion" },
      { title: 'Stargate', year: 1994, genre: "Ciencia Ficcion" },
      { title: 'Terminator 2: Judgment Day', year: 1991, genre: "Ciencia Ficcion" },
      { title: 'The Arrival', year: 2016, genre: "Ciencia Ficcion" },
      { title: 'The Fifth Element', year: 1997, genre: "Ciencia Ficcion" },
      { title: 'The Man from Earth', year: 2007, genre: "Ciencia Ficcion" },
      { title: 'The Martian', year: 2015, genre: "Ciencia Ficcion" },
      { title: 'The Matrix', year: 1999, genre: "Ciencia Ficcion" },
      { title: 'The Matrix Reloaded', year: 2003, genre: "Ciencia Ficcion" },
      { title: 'The Matrix Revolutions', year: 2003, genre: "Ciencia Ficcion" },
      { title: 'The Road', year: 2009, genre: "Ciencia Ficcion" },
      { title: 'The Terminator', year: 1984, genre: "Ciencia Ficcion" },
      { title: 'Total Recall', year: 1990, genre: "Ciencia Ficcion" },
      { title: 'Under the Skin', year: 2013, genre: "Ciencia Ficcion" },
      { title: 'Upgrade', year: 2018, genre: "Ciencia Ficcion" }
  ]
  
  let thriller = [
      { title: 'Along Came a Spider', year: 2001, genre: "Thriller" },
      { title: 'Beast', year: 2017, genre: "Thriller" },
      { title: 'Black Swan', year: 2010, genre: "Thriller" },
      { title: 'Bloodline', year: 2018, genre: "Thriller" },
      { title: "Carlito's Way", year: 1993, genre: "Thriller" },
      { title: 'Changeling', year: 2008, genre: "Thriller" },
      { title: 'Contratiempo', year: 2016, genre: "Thriller" },
      { title: 'Crash', year: 2004, genre: "Thriller" },
      { title: 'Derailed', year: 2005, genre: "Thriller" },
      { title: 'El Cuerpo', year: 2012, genre: "Thriller" },
      { title: 'Eyes Wide Shut', year: 1999, genre: "Thriller" },
      { title: 'Fight Club', year: 1999, genre: "Thriller" },
      { title: 'Frozen', year: 2010, genre: "Thriller" },
      { title: 'Gone Girl', year: 2014, genre: "Thriller" },
      { title: 'Hard Candy', year: 2005, genre: "Thriller" },
      { title: 'High Crimes', year: 2002, genre: "Thriller" },
      { title: 'I Saw the Devil', year: 2010, genre: "Thriller" },
      { title: 'Identity', year: 2003, genre: "Thriller" },
      { title: 'Insomnia', year: 2002, genre: "Thriller" },
      { title: 'Killer Joe', year: 2011, genre: "Thriller" },
      { title: 'Kiss the Girls', year: 1997, genre: "Thriller" },
      { title: 'Matchstick Men', year: 2003, genre: "Thriller" },
      { title: 'Memento', year: 2000, genre: "Thriller" },
      { title: 'Mr. Brooks', year: 2007, genre: "Thriller" },
      { title: 'Mulholland Drive', year: 2001, genre: "Thriller" },
      { title: 'Mulholland Falls', year: 1996, genre: "Thriller" },
      { title: 'Nightcrawler', year: 2014, genre: "Thriller" },
      { title: 'Phone Booth', year: 2002, genre: "Thriller" },
      { title: 'Pride and Glory', year: 2008, genre: "Thriller" },
      { title: 'Primal Fear', year: 1996, genre: "Thriller" },
      { title: 'Red Dragon', year: 2002, genre: "Thriller" },
      { title: 'Red Rooms', year: 2023, genre: "Thriller" },
      { title: 'Shutter Island', year: 2010, genre: "Thriller" },
      { title: 'Sleepers', year: 1996, genre: "Thriller" },
      { title: 'Taxi Driver', year: 1976, genre: "Thriller" },
      { title: 'The Bone Collector', year: 1999, genre: "Thriller" },
      { title: 'The Butterfly Effect', year: 2004, genre: "Thriller" },
      { title: 'The Crimson Rivers', year: 2000, genre: "Thriller" },
      { title: 'The Game', year: 1997, genre: "Thriller" },
      { title: "The Girl Who Kicked The Hornet's Nest", year: 2009, genre: "Thriller" },
      { title: 'The Girl Who Played With Fire', year: 2009, genre: "Thriller" },
      { title: 'The Girl With The Dragon Tattoo', year: 2009, genre: "Thriller" },
      { title: 'The Illusionist', year: 2006, genre: "Thriller" },
      { title: 'The Life of David Gale', year: 2003, genre: "Thriller" },
      { title: 'The Machinist', year: 2004, genre: "Thriller" },
      { title: 'The Manchurian Candidate', year: 2004, genre: "Thriller" },
      { title: 'The Mothman Prophecies', year: 2002, genre: "Thriller" },
      { title: 'The Others', year: 2001, genre: "Thriller" },
      { title: 'The Secret in Their Eyes', year: 2009, genre: "Thriller" },
      { title: 'The Silence of the Lambs', year: 1991, genre: "Thriller" },
      { title: 'The Sixth Sense', year: 1999, genre: "Thriller" },
      { title: 'The Stranger', year: 2022, genre: "Thriller" },
      { title: 'The Talented Mr. Ripley', year: 1999, genre: "Thriller" },
      { title: 'The Thomas Crown Affair', year: 1999, genre: "Thriller" },
      { title: 'The Village', year: 2004, genre: "Thriller" },
      { title: 'Thelma', year: 2017, genre: "Thriller" },
      { title: 'To Catch a Killer', year: 1992, genre: "Thriller" },
      { title: 'Wild Things', year: 1998, genre: "Thriller" }
  ]

  let misterio = [
      { title: 'Promising Young Woman', year: 2020, genre: "Misterio" },
      { title: 'The Gift', year: 2015, genre: "Misterio" },
      { title: 'Wind River', year: 2017, genre: "Misterio" }
  ]

  let deporte = [
      { title: 'Any Given Sunday', year: 1999, genre: "Deporte" },
      { title: 'Blue Chips', year: 1994, genre: "Deporte" },
      { title: 'Challengers', year: 2024, genre: "Deporte" },
      { title: 'Cinderella Man', year: 2005, genre: "Deporte" },
      { title: 'Coach Carter', year: 2005, genre: "Deporte" },
      { title: 'Ferrari', year: 2023, genre: "Deporte" },
      { title: 'Ford v Ferrari', year: 2019, genre: "Deporte" },
      { title: 'Invictus', year: 2009, genre: "Deporte" },
      { title: 'Iron Claw', year: 2023, genre: "Deporte" },
      { title: 'Million Dollar Baby', year: 2004, genre: "Deporte" },
      { title: 'Moneyball', year: 2011, genre: "Deporte" },
      { title: 'Raging Bull', year: 1980, genre: "Deporte" },
      { title: 'Real Steel', year: 2011, genre: "Deporte" },
      { title: 'Remember the Titans', year: 2000, genre: "Deporte" },
      { title: 'Rocky', year: 1976, genre: "Deporte" },
      { title: 'Rocky II', year: 1979, genre: "Deporte" },
      { title: 'Rocky III', year: 1982, genre: "Deporte" },
      { title: 'Rocky IV', year: 1985, genre: "Deporte" },
      { title: 'Rudy', year: 1993, genre: "Deporte" },
      { title: 'Seabiscuit', year: 2003, genre: "Deporte" },
      { title: 'Southpaw', year: 2015, genre: "Deporte" },
      { title: 'The Fighter', year: 2010, genre: "Deporte" },
      { title: 'The Wrestler', year: 2008, genre: "Deporte" },
      { title: 'Trouble with the Curve', year: 2012, genre: "Deporte" }
  ]
  
  let policial = [
      { title: 'A Bronx Tale', year: 1993, genre: "Policial" },
      { title: 'American Gangster', year: 2007, genre: "Policial" },
      { title: 'Blow', year: 2001, genre: "Policial" },
      { title: 'Casino', year: 1995, genre: "Policial" },
      { title: 'Catch Me If You Can', year: 2002, genre: "Policial" },
      { title: 'Donnie Brasco', year: 1997, genre: "Policial" },
      { title: 'End of Watch', year: 2012, genre: "Policial" },
      { title: 'Fargo', year: 1996, genre: "Policial" },
      { title: 'Goodfellas', year: 1990, genre: "Policial" },
      { title: 'Heat', year: 1995, genre: "Policial" },
      { title: 'Inside Man', year: 2006, genre: "Policial" },
      { title: 'L.A. Confidential', year: 1997, genre: "Policial" },
      { title: 'Mystic River', year: 2003, genre: "Policial" },
      { title: 'Prisoners', year: 2013, genre: "Policial" },
      { title: 'Pulp Fiction', year: 1994, genre: "Policial" },
      { title: 'Reservoir Dogs', year: 1992, genre: "Policial" },
      { title: 'Scarface', year: 1983, genre: "Policial" },
      { title: 'Serpico', year: 1973, genre: "Policial" },
      { title: 'Seven', year: 1995, genre: "Policial" },
      { title: 'Sicario', year: 2015, genre: "Policial" },
      { title: 'The Departed', year: 2006, genre: "Policial" },
      { title: 'The Godfather', year: 1972, genre: "Policial" },
      { title: 'The Godfather: Part II', year: 1974, genre: "Policial" },
      { title: 'The Untouchables', year: 1987, genre: "Policial" },
      { title: 'The Usual Suspects', year: 1995, genre: "Policial" },
      { title: 'Training Day', year: 2001, genre: "Policial" },
      { title: 'Zodiac', year: 2007, genre: "Policial" }
  ]
  
  let historia = [
      { title: '300', year: 2006, genre: "Historica" },
      { title: 'Agora', year: 2009, genre: "Historica" },
      { title: 'Apollo 13', year: 1995, genre: "Historica" },
      { title: 'Defiance', year: 2008, genre: "Historica" },
      { title: 'Gandhi', year: 1982, genre: "Historica" },
      { title: 'Gladiator', year: 2000, genre: "Historica" },
      { title: 'Hotel Rwanda', year: 2004, genre: "Historica" },
      { title: 'JFK', year: 1991, genre: "Historica" },
      { title: 'Kingdom of Heaven', year: 2005, genre: "Historica" },
      { title: 'Michael Collins', year: 1996, genre: "Historica" },
      { title: 'Munich', year: 2005, genre: "Historica" },
      { title: 'Pearl Harbor', year: 2001, genre: "Historica" },
      { title: 'Selma', year: 2014, genre: "Historica" },
      { title: 'The Imitation Game', year: 2014, genre: "Historica" },
      { title: 'The Iron Lady', year: 2011, genre: "Historica" },
      { title: 'The Passion of the Christ', year: 2004, genre: "Historica" },
      { title: 'Troy', year: 2004, genre: "Historica" },
      { title: 'Valkyrie', year: 2008, genre: "Historica" }
  ]
  
  let reales = [
      { title: '127 Hours', year: 2010, genre: "Basada en Hechos Reales" },
      { title: 'Argo', year: 2012, genre: "Basada en Hechos Reales" },
      { title: 'Captain Phillips', year: 2013, genre: "Basada en Hechos Reales" },
      { title: 'Dallas Buyers Club', year: 2013, genre: "Basada en Hechos Reales" },
      { title: 'Erin Brockovich', year: 2000, genre: "Basada en Hechos Reales" },
      { title: 'Frost/Nixon', year: 2008, genre: "Basada en Hechos Reales" },
      { title: 'Monster', year: 2003, genre: "Basada en Hechos Reales" },
      { title: 'October Sky', year: 1999, genre: "Basada en Hechos Reales" },
      { title: 'Spotlight', year: 2015, genre: "Basada en Hechos Reales" },
      { title: 'The Big Short', year: 2015, genre: "Basada en Hechos Reales" },
      { title: 'The Last King of Scotland', year: 2006, genre: "Basada en Hechos Reales" },
      { title: 'The Social Network', year: 2010, genre: "Basada en Hechos Reales" },
      { title: 'The Soloist', year: 2009, genre: "Basada en Hechos Reales" },
      { title: 'The Theory of Everything', year: 2014, genre: "Basada en Hechos Reales" },
      { title: 'Zero Dark Thirty', year: 2012, genre: "Basada en Hechos Reales" }
  ]
  
  let biopics = [
      { title: 'A Beautiful Mind', year: 2001, genre: "Biopics" },
      { title: 'Man on the Moon', year: 1999, genre: "Biopics" },
      { title: 'The Aviator', year: 2004, genre: "Biopics" },
      { title: 'The Doors', year: 1991, genre: "Biopics" },
      { title: 'The Motorcycle Diaries', year: 2004, genre: "Biopics" },
      { title: 'The People vs. Larry Flynt', year: 1996, genre: "Biopics" }
  ]
  
  let romanticas = [
      { title: 'As Good as It Gets', year: 1997, genre: "Romanticas" },
      { title: 'Before Sunrise', year: 1995, genre: "Romanticas" },
      { title: 'Before Sunset', year: 2004, genre: "Romanticas" },
      { title: 'Eternal Sunshine of the Spotless Mind', year: 2004, genre: "Romanticas" },
      { title: 'Notting Hill', year: 1999, genre: "Romanticas" },
      { title: 'Silver Linings Playbook', year: 2012, genre: "Romanticas" },
      { title: 'The Bridges of Madison County', year: 1995, genre: "Romanticas" },
      { title: 'The Fault in Our Stars', year: 2014, genre: "Romanticas" },
      { title: 'When Harry Met Sally...', year: 1989, genre: "Romanticas" }
  ]
  
  let musica =  [
      { title: '8 Mile', year: 2002, genre: "Musica" },
      { title: 'A Star is Born', year: 2018, genre: "Musica" },
      { title: 'Almost Famous', year: 2000, genre: "Musica" },
      { title: 'Amadeus', year: 1984, genre: "Musica" },
      { title: 'Birdman', year: 2014, genre: "Musica" },
      { title: 'Bohemian Rhapsody', year: 2018, genre: "Musica" },
      { title: 'High Fidelity', year: 2000, genre: "Musica" },
      { title: 'Ray', year: 2004, genre: "Musica" },
      { title: 'Shine', year: 1996, genre: "Musica" },
      { title: 'Whiplash', year: 2014, genre: "Musica" }
  ]
  
  let cineNoir = [
      {"title": "Drive", "year": 2011, genre: "Cine Noir"}
  ]

  let belicas = [
      { title: '1917', year: 2019, genre: "Belica" },
      { title: 'All Quiet on the Western Front', year: 2022, genre: "Belica" },
      { title: 'Apocalypse Now', year: 1979, genre: "Belica" },
      { title: 'Black Hawk Down', year: 2001, genre: "Belica" },
      { title: 'Braveheart', year: 1995, genre: "Belica" },
      { title: 'Dunkirk', year: 2017, genre: "Belica" },
      { title: 'Enemy at the Gates', year: 2001, genre: "Belica" },
      { title: 'Fury', year: 2014, genre: "Belica" },
      { title: 'Inglourious Basterds', year: 2009, genre: "Belica" },
      { title: 'Saving Private Ryan', year: 1998, genre: "Belica" },
      { title: "Schindler's List", year: 1993, genre: "Belica" },
      { title: 'The Boy in the Striped Pyjamas', year: 2008, genre: "Belica" },
      { title: 'The Hurt Locker', year: 2008, genre: "Belica" },
      { title: 'The Pianist', year: 2002, genre: "Belica" },
      { title: 'The Thin Red Line', year: 1998, genre: "Belica" }
  ]

  let drama = [
      { title: '12 Angry Men', year: 1957, genre: "Drama" },      
      { title: '12 Years a Slave', year: 2013, genre: "Drama" },  
      { title: '50/50', year: 2011, genre: "Drama" },
      { title: 'A Beautiful Mind', year: 2001, genre: "Drama" },  
      { title: 'A Clockwork Orange', year: 1971, genre: "Drama" },
      { title: 'A Perfect Murder', year: 1998, genre: "Drama" },  
      { title: 'American Beauty', year: 1999, genre: "Drama" },   
      { title: 'American History X', year: 1998, genre: "Drama" },
      { title: 'American Sniper', year: 2014, genre: "Drama" },   
      { title: 'Apt Pupil', year: 1998, genre: "Drama" },
      { title: 'Awakenings', year: 1990, genre: "Drama" },        
      { title: 'Babel', year: 2006, genre: "Drama" },
      { title: 'Birth/Rebirth', year: 2023, genre: "Drama" },     
      { title: 'Buried', year: 2010, genre: "Drama" },
      { title: 'Cast Away', year: 2000, genre: "Drama" },
      { title: 'Christine', year: 2016, genre: "Drama" },
      { title: 'Cidade de Deus', year: 2002, genre: "Drama" },    
      { title: 'Cinema Paradiso', year: 1988, genre: "Drama" },   
      { title: 'Citizen X', year: 1995, genre: "Drama" },
      { title: 'Coda', year: 2021, genre: "Drama" },
      { title: 'Compliance', year: 2012, genre: "Drama" },        
      { title: 'Die Welle', year: 2008, genre: "Drama" },
      { title: 'Downfall', year: 2004, genre: "Drama" },
      { title: 'El secreto de sus ojos', year: 2009, genre: "Drama" },
      { title: 'Forrest Gump', year: 1994, genre: "Drama" },
      { title: 'Good Will Hunting', year: 1997, genre: "Drama" },
      { title: 'House of Sand and Fog', year: 2003, genre: "Drama" },
      { title: 'Interview with the Vampire', year: 1994, genre: "Drama" },
      { title: 'Into the Wild', year: 2007, genre: "Drama" },
      { title: 'John Q', year: 2002, genre: "Drama" },
      { title: 'La Pianiste', year: 2001, genre: "Drama" },
      { title: 'Les Miserables', year: 2012, genre: "Drama" },
      { title: 'Life is beautiful', year: 1997, genre: "Drama" },
      { title: 'Lord of War', year: 2005, genre: "Drama" },
      { title: 'Match Point', year: 2005, genre: "Drama" },
      { title: 'Misery', year: 1990, genre: "Drama" },
      { title: "Mr. Holland's Opus", year: 1995, genre: "Drama" },
      { title: 'Of Mice and Men', year: 1992, genre: "Drama" },
      { title: "One Flew Over the Cuckoo's Nest", year: 1975, genre: "Drama" },
      { title: 'Pay it Forward', year: 2000, genre: "Drama" },
      { title: 'Philadelphia', year: 1993, genre: "Drama" },
      { title: 'Reign Over Me', year: 2007, genre: "Drama" },
      { title: 'Return to Paradise', year: 1998, genre: "Drama" },
      { title: 'Room', year: 2015, genre: "Drama" },
      { title: 'Scent of a Woman', year: 1992, genre: "Drama" },
      { title: 'Still Alice', year: 2014, genre: "Drama" },
      { title: 'Sunshine', year: 2007, genre: "Drama" },
      { title: 'The Aviator', year: 2004, genre: "Drama" },
      { title: 'The Basketball Diaries', year: 1995, genre: "Drama" },
      { title: 'The Book Thief', year: 2013, genre: "Drama" },
      { title: 'The Bucket List', year: 2007, genre: "Drama" },
      { title: 'The Danish Girl', year: 2015, genre: "Drama" },
      { title: 'The Dead Poets Society', year: 1989, genre: "Drama" },
      { title: 'The Deer Hunter', year: 1978, genre: "Drama" },
      { title: "The Devil's Advocate", year: 1997, genre: "Drama" },
      { title: 'The English Patient', year: 1996, genre: "Drama" },
      { title: 'The Green Mile', year: 1999, genre: "Drama" },
      { title: 'The Hunt', year: 2012, genre: "Drama" },
      { title: 'The Impossible', year: 2012, genre: "Drama" },
      { title: 'The Judge', year: 2014, genre: "Drama" },
      { title: 'The King’s Speech', year: 2010, genre: "Drama" },
      { title: 'The Lives of Others', year: 2006, genre: "Drama" },
      { title: 'The Prestige', year: 2006, genre: "Drama" },
      { title: 'The Pursuit of Happyness', year: 2006, genre: "Drama" },
      { title: 'The Shawshank Redemption', year: 1994, genre: "Drama" },
      { title: 'The Truman Show', year: 1998, genre: "Drama" },
      { title: 'Thirteen', year: 2003, genre: "Drama" },
      { title: 'Titanic', year: 1997, genre: "Drama" }
  ]
  
  let terror = [
      { title: '10 Cloverfield Lane', year: 2016, genre: "Terror" },  
      { title: '13 Sins', year: 2014, genre: "Terror" },
      { title: 'A Tale of Two Sisters', year: 2003, genre: "Terror" },
      { title: 'American Mary', year: 2012, genre: "Terror" },        
      { title: 'Antichrist', year: 2009, genre: "Terror" },
      { title: 'As Above So Below', year: 2014, genre: "Terror" },    
      { title: 'Audition', year: 1999, genre: "Terror" },
      { title: 'Barbarian', year: 2022, genre: "Terror" },
      { title: 'Bliss', year: 2019, genre: "Terror" },
      { title: 'Bone Tomahawk', year: 2015, genre: "Terror" },        
      { title: 'Bones and All', year: 2022, genre: "Terror" },        
      { title: 'Brightwood', year: 2023, genre: "Terror" },
      { title: 'Candyman', year: 1992, genre: "Terror" },
      { title: 'Carrie', year: 1976, genre: "Terror" },
      { title: 'Caveat', year: 2020, genre: "Terror" },
      { title: 'Censor', year: 2021, genre: "Terror" },
      { title: 'Damien: Omen 2', year: 1978, genre: "Terror" },
      { title: 'Devil', year: 2010, genre: "Terror" },
      { title: "Don't Breathe", year: 2016, genre: "Terror" },
      { title: 'Dread', year: 2009, genre: "Terror" },
      { title: 'Eat', year: 2014, genre: "Terror" },
      { title: 'Eden Lake', year: 2008, genre: "Terror" },
      { title: 'Evil Dead', year: 2013, genre: "Terror" },
      { title: 'Evil Dead Rise', year: 2023, genre: "Terror" },
      { title: 'Fresh', year: 2022, genre: "Terror" },
      { title: 'Frontiers', year: 2007, genre: "Terror" },
      { title: "Gerald's Game", year: 2017, genre: "Terror" },
      { title: 'Get Out', year: 2017, genre: "Terror" },
      { title: 'Goodnight Mommy', year: 2014, genre: "Terror" },
      { title: 'Green Room', year: 2015, genre: "Terror" },
      { title: 'Hellraiser', year: 1987, genre: "Terror" },
      { title: 'Hereditary', year: 2018, genre: "Terror" },
      { title: 'High Tension', year: 2003, genre: "Terror" },
      { title: 'Honeymoon', year: 2014, genre: "Terror" },
      { title: 'Hostel', year: 2005, genre: "Terror" },
      { title: 'Housewife', year: 2017, genre: "Terror" },
      { title: 'Incident in a Ghostland', year: 2018, genre: "Terror" },
      { title: 'Infinity Pool', year: 2023, genre: "Terror" },
      { title: 'Inside', year: 2007, genre: "Terror" },
      { title: 'Irreversible', year: 2002, genre: "Terror" },
      { title: 'It', year: 2017, genre: "Terror" },
      { title: 'It', year: 1990, genre: "Terror" },
      { title: 'It Comes at Night', year: 2017, genre: "Terror" },
      { title: 'It Follows', year: 2014, genre: "Terror" },
      { title: "Jacob's Ladder", year: 1990, genre: "Terror" },
      { title: 'Kandisha', year: 2020, genre: "Terror" },
      { title: 'Koko-di Koko-da', year: 2019, genre: "Terror" },
      { title: 'Kol', year: 2020, genre: "Terror" },
      { title: 'Kotoko', year: 2011, genre: "Terror" },
      { title: 'Last Shift', year: 2014, genre: "Terror" },
      { title: 'Let the Right One In', year: 2008, genre: "Terror" },
      { title: 'Martyrs', year: 2008, genre: "Terror" },
      { title: 'Midsommar', year: 2019, genre: "Terror" },
      { title: 'Moloch', year: 2022, genre: "Terror" },
      { title: 'Nefarious', year: 2023, genre: "Terror" },
      { title: 'No One Will Save You', year: 2023, genre: "Terror" },
      { title: 'Nocturne', year: 2010, genre: "Terror" },
      { title: "Pan's Labyrinth", year: 2006, genre: "Terror" },
      { title: 'Pearl', year: 2022, genre: "Terror" },
      { title: 'Pet Sematary', year: 1989, genre: "Terror" },
      { title: 'Pyewacket', year: 2017, genre: "Terror" },
      { title: 'Raw', year: 2016, genre: "Terror" },
      { title: 'REC', year: 2007, genre: "Terror" },
      { title: 'Relic', year: 2020, genre: "Terror" },
      { title: 'Resolution', year: 2012, genre: "Terror" },
      { title: 'Resurrected', year: 2023, genre: "Terror" },
      { title: 'Resurrection', year: 2022, genre: "Terror" },
      { title: 'Revenge', year: 2017, genre: "Terror" },
      { title: "Rosemary's Baby", year: 1968, genre: "Terror" },
      { title: 'Saint Maud', year: 2019, genre: "Terror" },
      { title: 'Saw', year: 2004, genre: "Terror" },
      { title: 'Scream', year: 1996, genre: "Terror" },
      { title: 'Shelley', year: 2016, genre: "Terror" },
      { title: 'Sinister', year: 2012, genre: "Terror" },
      { title: 'Soft & Quiet', year: 2022, genre: "Terror" },
      { title: 'Speak No Evil', year: 2022, genre: "Terror" },
      { title: 'Spring', year: 2014, genre: "Terror" },
      { title: 'Stigmata', year: 1999, genre: "Terror" },
      { title: 'Storm of the Century', year: 1999, genre: "Terror" },
      { title: 'Talk to Me', year: 2022, genre: "Terror" },
      { title: 'The Advent Calendar', year: 2021, genre: "Terror" },
      { title: 'The Autopsy of Jane Doe', year: 2016, genre: "Terror" },
      { title: 'The Babadook', year: 2014, genre: "Terror" },
      { title: 'The Battery', year: 2012, genre: "Terror" },
      { title: 'The Beach House', year: 2019, genre: "Terror" },
      { title: "The Blackcoat's Daughter", year: 2015, genre: "Terror" },
      { title: 'The Blair Witch Project', year: 1999, genre: "Terror" },
      { title: 'The Cabin in the Woods', year: 2012, genre: "Terror" },
      { title: 'The Conjuring', year: 2013, genre: "Terror" },
      { title: 'The Conjuring 2', year: 2016, genre: "Terror" },
      { title: 'The Dark and the Wicked', year: 2020, genre: "Terror" },
      { title: 'The Descent', year: 2005, genre: "Terror" },
      { title: "The Devil's Candy", year: 2015, genre: "Terror" },
      { title: 'The Empty Man', year: 2020, genre: "Terror" },
      { title: 'The Exorcism of Emily Rose', year: 2005, genre: "Terror" },
      { title: 'The Exorcist', year: 1973, genre: "Terror" },
      { title: 'The Eyes of My Mother', year: 2016, genre: "Terror" },
      { title: 'The Feast', year: 2021, genre: "Terror" },
      { title: 'The Innocents', year: 2021, genre: "Terror" },
      { title: 'The Invitation', year: 2015, genre: "Terror"},
      { title: 'The Lazarus Effect', year: 2015, genre: "Terror" },
      { title: 'The Lighthouse', year: 2019, genre: "Terror" },
      { title: 'The Lodge', year: 2019, genre: "Terror" },
      { title: 'The Mothman Prophecies', year: 2002, genre: "Terror" },
      { title: 'The Neon Demon', year: 2016, genre: "Terror" },
      { title: 'The Night House', year: 2021, genre: "Terror" },
      { title: 'The Omen', year: 1976, genre: "Terror" },
      { title: 'The Orphanage', year: 2007, genre: "Terror" },
      { title: 'The Others', year: 2001, genre: "Terror" },
      { title: 'The Perfection', year: 2018, genre: "Terror" },
      { title: 'The Ring', year: 2002, genre: "Terror" },
      { title: 'The Ritual', year: 2017, genre: "Terror" },
      { title: 'The Sadness', year: 2021, genre: "Terror" },
      { title: 'The Shining', year: 1980, genre: "Terror" },
      { title: 'The Skeleton Key', year: 2005, genre: "Terror" },
      { title: 'The Strangers', year: 2008, genre: "Terror" },
      { title: 'The Visit', year: 2015, genre: "Terror" },
      { title: 'The Wailing', year: 2016, genre: "Terror" },
      { title: 'The Witch', year: 2015, genre: "Terror" },
      { title: 'Triangle', year: 2009, genre: "Terror" },
      { title: 'Unfriended: Dark Web', year: 2018, genre: "Terror" },
      { title: 'Unsane', year: 2018, genre: "Terror" },
      { title: 'Violation', year: 2020, genre: "Terror" },
      { title: 'What Keeps You Alive', year: 2018, genre: "Terror" },
      { title: 'Wolf Creek', year: 2005, genre: "Terror" },
      { title: 'X', year: 2022, genre: "Terror" }
  ]
  
  
  let peliculas = { accion, argentinas, comedias, fantastico, aventura, csFiccion, thriller, misterio, deporte, policial, historia, reales, biopics, romanticas, musica,
     cineNoir, belicas, drama, terror }

let otrosGeneros = [...accion, ...argentinas, ...comedias, ...fantastico, ...aventura, ...csFiccion, ...thriller, ...misterio, ...deporte, ...policial, ...historia, ...reales, ...biopics, ...romanticas, ...musica,
...cineNoir, ...belicas, ...drama]
  // console.log(terror.horror_movies[1])
  // let terror2 = accion.accion.sort((a, b) => a.title.localeCompare(b.title));
//   console.log(util.inspect(otrosGeneros, { showHidden: false, depth: null, maxArrayLength: null }))
//   console.log(otrosGeneros.length)
//   console.log(typeof otrosGeneros)
  // console.log(accion.length + argentinas.length + comedias.length + fantastico.length + aventura.length + csFiccion.length + thriller.length + misterio.length + deporte.length +
  //    policial.length + historia.length + reales.length + biopics.length + romanticas.length + musica.length + cineNoir.length + belicas.length + drama.length + terror.length)

  module.exports = { peliculas, otrosGeneros, terror }